// #include "dataset_test.hpp"
// #include "maxbuffer_test.hpp"
#include "maxbuffercollection_test.hpp"
// #include "collection_test.hpp"
// #include "similarity_measure_test.hpp"
// #include "format_test.hpp"
// #include "prefixmap_test.hpp"
// #include "hash_test.hpp"
// #include "hash_source_test.hpp"
// #include "filterer_test.hpp"
// #include "math_test.hpp"
// #include "sorthash_test.hpp"
