
name: Puffinn

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel the workflow for the previous commit when the new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3 # Pull the repository
      - run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy
      - run: |
          mkdir build && cd build
          cmake .. && make
          ./Test

  run-benchmarks:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v3 # Pull the repository

    - name: Install OS Dependencies
      run: sudo apt-get update && sudo apt-get install -y libhdf5-dev

    - name: Install Project Dependencies
      run: pip3 install numpy pybind11[global]

    - name: Install and run example
      run: |
        pip3 install .
        python3 examples/random-vectors.py
